name: TransferUI
main: TransferUI\Main
api: [3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
version: 0.0.2
author: BajanVlogs

commands:
 server:
  description: "This is for transfering servers using CustomUI"
